var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};
$jscomp.polyfill=function(a,b,c,e){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,e):$jscomp.polyfillUnisolated(a,b,c,e))};$jscomp.polyfillUnisolated=function(a,b,c,e){c=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var d=a[e];if(!(d in c))return;c=c[d]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,e){var d=a.split(".");a=1===d.length;e=d[0];e=!a&&e in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<d.length-1;f++){var g=d[f];if(!(g in e))return;e=e[g]}d=d[d.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?e[d]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,d,{configurable:!0,writable:!0,value:b}):b!==c&&(void 0===$jscomp.propertyToPolyfillSymbol[d]&&(c=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[d]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(d):$jscomp.POLYFILL_PREFIX+c+"$"+d),$jscomp.defineProperty(e,$jscomp.propertyToPolyfillSymbol[d],{configurable:!0,writable:!0,value:b})))};
$jscomp.polyfill("String.prototype.replaceAll",function(a){return a?a:function(b,c){if(b instanceof RegExp&&!b.global)throw new TypeError("String.prototype.replaceAll called with a non-global RegExp argument.");return b instanceof RegExp?this.replace(b,c):this.replace(new RegExp(String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),c)}},"es_2021","es3");
$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var e=a.length,d=0;d<e;d++){var f=a[d];if(b.call(c,f,d,a))return{i:d,v:f}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(b,c){return $jscomp.findInternal(this,b,c).v}},"es6","es3");IP=dsf;PORT=62626;PROTOCOL="ws";
var sendBtn=document.querySelector("#tosendb"),authBtn=document.querySelector("#tosendb_auth"),pingSnd=new Audio("https://llimeon.github.io/battleship-client/sounds/ping.ogg"),ustate=0,name="None",u_id=11111,sound_set=!1,perem=0,send_end=0;window.addEventListener("focus",function(a){console.log("focus");sound_set=!1;console.log(sound_set)});window.addEventListener("blur",function(a){console.log("blur");sound_set=!0;console.log(sound_set)});socket=new WebSocket(PROTOCOL+"://"+IP+":"+PORT);
socket.onmessage=function(a){sound_set&&(console.log(sound_set),pingSnd.play());a=JSON.parse(a.data);console.log(a);switch(a.type){case "pong":console.log("pong!");break;case "connection":1==a.agree_connect?(st_ty(),name=a.name,ustate=1,send_b.hidden=!1,reg_bl.hidden=!0,sh_b.hidden=!0,chat_a.hidden=!1):console.log("error!");break;case "message":data=decodeURI(a.text);data=data.replace(/(?:\r\n|\r|\n)/g,"</br>");name_m=decodeURI(a.name);p=document.createElement("p");p.innerHTML="<code>"+name_m+"</code>: "+
data;p.setAttribute("onclick","this.hidden = true");contm.append(p);chatik.scrollBy(0,1E3);break;case "connection_error":reason=a.response;a="<div class='block_e'><div class='poof'><p class='error_text'>"+reason+"</p></div></div>";$("#tm_a").append(a);setTimeout(function(){$(".block_e")[0].remove()},3E3);break;case "typing":switch(a.text){case "start":a='<p style="margin:0; margin-top:2px;" class=\'items_'+a.name+"'>"+a.name+" \u043f\u0435\u0447\u0430\u0442\u0430\u0435\u0442..</p>";$("#tp_bv").append(a);
break;case "stop":$(".items_"+a.name)[0].remove()}}return!1};function typing(){0<perem?--perem:1>perem&&1==send_end&&(send_end=0,socket.send(JSON.stringify({type:"typing",text:"stop",name:name})));console.log(perem)}
snd_v.addEventListener("keydown",function(a){"Enter"!=a.key&&(0==send_end&&(send_end=1,socket.send(JSON.stringify({type:"typing",text:"start",name:name}))),perem=5);if("Enter"===a.key&&!a.shiftKey)return perem=0,console.log("send! m"),console.log(snd_v.innerHTML),rtm=snd_v.innerHTML,mgf=rtm.replaceAll("<div>","\n").replaceAll("<br>","\n"),console.log(mgf),data=encodeURI(mgf),console.log(data),socket.send(JSON.stringify({type:"message",text:data,name:name})),a=$("#snd_v").val().split("\n").length,
snd_v.innerHTML="",console.log(a),snd_v.style.height="15px",console.log("----------------------------"),setTimeout('ider = $("#snd_v").find("div").length; if (ider) {console.log(ider); $("#snd_v div").remove()};',50),!1;if("Enter"===a.key&&a.shiftKey){a=document.createElement("br");var b=window.getSelection().getRangeAt(0);b.deleteContents();b.insertNode(a);b.collapse();blankSpace=$("#snd_v").find("br").length;trn=$("#snd_v").find("div").length;console.log(" --- "+blankSpace+" - "+(trn-1));snd_v.style.height=
15*blankSpace+15*trn+15+"px"}return!1});tosendb_auth.addEventListener("mouseenter",function(a){console.log("enter!");anime({targets:"#tosendb_auth",width:"140",delay:200,backgroundColor:"#404040"})});tosendb_auth.addEventListener("mouseleave",function(a){console.log("leave!");anime({targets:"#tosendb_auth",width:"200",delay:300,backgroundColor:"#323232"})});area_auth.addEventListener("focus",function(a){console.log("focus");anime({targets:"#area_auth",borderRadius:"5px",width:"270"})});
area_auth.addEventListener("blur",function(a){console.log("blur");anime({targets:"#area_auth",width:"200"})});area_auth_pass.addEventListener("focus",function(a){console.log("focus");anime({targets:"#area_auth_pass",borderRadius:"5px",width:"270"})});area_auth_pass.addEventListener("blur",function(a){console.log("blur");anime({targets:"#area_auth_pass",width:"200"})});function st_ty(){setInterval(function(){typing()},1E3)}
authBtn.addEventListener("click",function(a){console.log("send!");data=encodeURI(area_auth.value);socket.send(JSON.stringify({type:"auth",ustate:ustate,text:data,name:name,pass:area_auth_pass.value,variant:variant.value}));return!1});socket.onopen=function(){$("#tm_a").append("<div class='block_e'><div class='poof'><p class='error_text'>server connected</p></div></div>");setTimeout(function(){$(".block_e")[0].remove()},3E3);console.log("Connected.")};
socket.onclose=function(a){$("#tm_a").append("<div class='block_e'><div class='poof'><p class='error_text'>close connect</p></div></div>");setTimeout(function(){$(".block_e")[0].remove()},3E3);a.wasClean?(setTimeout(function(){return function(){try{console.log("Reconect.."),socket=new WebSocket(PROTOCOL+"://"+IP+":"+PORT)}catch(b){console.log("Reconected!"),console.log("Code: "+a.code+" reason: "+a.reason)}}},5),console.log("Close connection")):(console.log("Connection fail"),alert_text="Fail to connect to server")};
socket.onerror=function(a){var b="<div class='block_e'><div class='poof'><p class='error_text'>error: "+a.message+"</p></div></div>";$("#tm_a").append(b);setTimeout(function(){$(".block_e")[0].remove()},3E3);console.log("Error "+a.message)};
